collections:
  weeknotes:
    output: true
    permalink: weeknotes/:path/
  playbook:
    output: true
    permalink: playbook/:path/
  projects:
    output: true
    status: true
    permalink: projects/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "playbook"
    values:
      layout: "post"
